# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Teach the Teachers August 2017
email: teachtheteachers2016@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A repository of reflections and examples from the Teach the Teachers Workshop, August 2017
baseurl: "/TeachtheTeachersTreebanks" # the subpath of your site, e.g. /blog
url: "https://perseids-project.github.io/TeachtheTeachersTreebanks/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PerseidsProject
github_username:  TDBuck
DOI : your DOI here
# Build settings
markdown: kramdown
theme: jekyll-theme-slate
gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock


# below are the changes you will need to make to the config file to make the widget and collections work 
# this is not a fully functional config file on its own
# you will also change the desitnation element in your default config file to the following
destination: docs
# the rest of this you can add to the bottom of your config file
collections:
  tbpages:
    output: true
    permalink: :title.html
assets:
  assets:
    - "*.json"
    - "*.js"
    - "*.css"
    - "*.png"
    - "*.ttf"
    - "*.svg"
    - "*.eot"
    - "*.otf"
    - "*.woff"
  sources:
    - _assets/arethusa






